const AMMO=[{id:'frost',n:'Frost',k:'1',c:'#7ec8e3'},{id:'flare',n:'Flare',k:'2',c:'#e8a317'},{id:'antidote',n:'Antidote',k:'3',c:'#7cb342'},{id:'rope',n:'Rope',k:'4',c:'#d4a574'},{id:'sonic',n:'Sonic',k:'5',c:'#c084fc'},{id:'ap',n:'Pierce',k:'6',c:'#b0bec5'},{id:'tranq',n:'Tranq',k:'7',c:'#80cbc4'}];
const BESTIARY={wyvern:{name:'Ash-Wyvern',weak:'frost',tell:'Wings lock before the dive. Frost the joints and it falls.',hp:4,sp:1.05,dmg:24,draw:'wyvern'},ironhide:{name:'Ironhide',weak:'ap',tell:'The throat-plate lifts when it charges. Pierce there.',hp:5,sp:.48,dmg:20,draw:'iron'},drake:{name:'Field Drake',weak:'flare',tell:'It blinks before it breathes. A flare in the eye stops the fire.',hp:3,sp:.9,dmg:18,draw:'drake'},stag:{name:'Corrupted Stag',weak:'tranq',tell:'Black sap runs the antlers. A dart in the neck stills it.',hp:4,sp:.7,dmg:18,draw:'stag'},wraith:{name:'Hex-Wraith',weak:'sonic',tell:'The core beats in the ribs. Sound cracks the binding.',hp:3,sp:1.05,dmg:22,draw:'wraith'},coil:{name:'Venom Hydra',weak:'antidote',tell:'Fangs wet before the strike. Antidote on the shaft.',hp:4,sp:.88,dmg:24,draw:'hydra'},roc:{name:'Cliff Roc',weak:'rope',tell:'It hangs at the apex. Bind a wing and gravity does the rest.',hp:5,sp:.85,dmg:26,draw:'roc'}};
const CONTRACTS=[{t:'Hold the road',d:'Wyverns and hydras on the caravan route.',w:3,k:['wyvern','ironhide','coil']},{t:'Hunt the marked one',d:'One prize beast. You, the bow, the kill.',w:1,k:['stag','roc','wyvern'],e:1},{t:'Guard the fields',d:'A drake and its court are in the grain.',w:4,k:['drake','stag','wraith']},{t:'Break the nest',d:'The brood-mother first. Then whatever hatches.',w:2,k:['coil','roc','ironhide'],e:1}];
const canvas=document.getElementById('c'),ctx=canvas.getContext('2d'),ov=document.getElementById('ov'),logEl=document.getElementById('log'),bar=document.getElementById('bar');
let dpr=1,state='menu',ammo='frost',hp=100,mat=0,wn=0,con=null,wave=0,beasts=[],arrows=[],bits=[],observe=0,studying=0,aim={x:400,y:240},pull=0,kick=0,logs=[],busy=0,cool=0,t=0;
function size(){const r=canvas.getBoundingClientRect();dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,r.width*dpr);canvas.height=Math.max(1,r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',size);
function say(m){logs.unshift(m);logs=logs.slice(0,4);logEl.innerHTML=logs.map(s=>'<div>'+s+'</div>').join('')}
function hud(){document.getElementById('hp').textContent=Math.max(0,Math.ceil(hp));document.getElementById('mat').textContent=mat;document.getElementById('wn').textContent=wn}
function ammoUI(){bar.innerHTML=AMMO.map(a=>'<button class="am '+(a.id===ammo?'on':'')+'" data-id="'+a.id+'">'+a.k+' '+a.n+'</button>').join('')+'<span style="margin-left:auto;color:#9a8b70">Shift studies the beast \u00b7 click looses</span>';bar.querySelectorAll('.am').forEach(b=>b.onclick=()=>{ammo=b.dataset.id;ammoUI()})}
function menu(title,body){state='menu';busy=0;ov.classList.add('show');const box=document.getElementById('menu');if(title)box.innerHTML='<h2>'+title+'</h2><p>'+body+'</p><div class="g" id="cs"></div>';const host=document.getElementById('cs');if(!host)return;host.innerHTML=CONTRACTS.map((c,i)=>'<button data-i="'+i+'"><b>'+c.t+'</b><i>'+c.d+'</i></button>').join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>start(CONTRACTS[+b.dataset.i]))}
function start(c){con=c;wave=0;beasts=[];arrows=[];bits=[];observe=0;studying=0;busy=0;hp=100;hud();ov.classList.remove('show');state='play';size();say('You take the wall. '+c.t+'.');spawn()}
function spawn(){wave++;busy=0;beasts=beasts.filter(b=>b.ok);const n=con.e?1:1+Math.min(2,wave-1);const cw=canvas.clientWidth||900,ch=canvas.clientHeight||520;for(let i=0;i<n;i++){const key=con.k[(wave+i-1)%con.k.length],p=BESTIARY[key],extra=(con.e?2:0)+(wave>2?1:0);beasts.push(Object.assign({},p,{key,x:cw*0.56+Math.random()*cw*0.28,y:ch*0.28+Math.random()*ch*0.26,z:0.36+Math.random()*0.2,ph:Math.random()*6.28,hp:p.hp+extra,max:p.hp+extra,rev:0,flash:0,ok:1,atk:0}))}say('On the approach: '+beasts.filter(b=>b.ok).map(b=>b.name).join(', '))}
function burst(x,y,c,n){for(let i=0;i<n;i++)bits.push({x,y,vx:(Math.random()-.5)*220,vy:(Math.random()-.5)*180-30,life:.5,c,s:2+Math.random()*3})}
function nearAt(x,y){let best=null,d=1e9;for(const b of beasts){if(!b.ok)continue;const s=34+b.z*80,k=Math.hypot(b.x-x,b.y-y);if(k<d&&k<s){d=k;best=b}}return best}
function shoot(){if(state!=='play'||cool>0)return;cool=.2;pull=1;kick=5;arrows.push({x:canvas.clientWidth*.5,y:canvas.clientHeight*.64,tx:aim.x,ty:aim.y,ammo,t:0})}
function strike(b,type){const good=type===b.weak;b.hp-=good?b.max:1;b.flash=.28;burst(b.x,b.y,good?'#d4b45a':'#777',good?22:8);say(good?(b.name+' takes the '+type+' where it lives.'):(b.name+' wears the shot. Study it.'));if(b.hp<=0){b.ok=0;const pay=10+(con.e?14:0)+wave*2;mat+=pay;hud();burst(b.x,b.y,'#6a2020',28);say(b.name+' is down. +'+pay+' materials.')}}
function lose(){if(state!=='play')return;state='menu';menu('The village burns','You were on the wall and it was not enough. The next watch starts clean.')}
function win(){if(state!=='play')return;wn++;mat+=24+wave*5;hud();state='menu';menu('The watch is kept','They are still alive below because a man stood here and shot. Take the next one.')}
function sky(cw,ch){const g=ctx.createLinearGradient(0,0,0,ch);g.addColorStop(0,'#1a2433');g.addColorStop(.42,'#2a2a20');g.addColorStop(1,'#1a1c14');ctx.fillStyle=g;ctx.fillRect(0,0,cw,ch);ctx.fillStyle='#cfc6a8';ctx.beginPath();ctx.arc(cw*.84,ch*.14,22,0,7);ctx.fill();ctx.fillStyle='rgba(207,198,168,.12)';ctx.beginPath();ctx.arc(cw*.84,ch*.14,48,0,7);ctx.fill();ctx.fillStyle='#162016';ctx.beginPath();ctx.moveTo(0,ch*.56);for(let x=0;x<=cw;x+=28)ctx.lineTo(x,ch*.52+Math.sin(x*.016)*20);ctx.lineTo(cw,ch);ctx.lineTo(0,ch);ctx.fill();ctx.fillStyle='#1e2818';ctx.beginPath();ctx.moveTo(0,ch*.70);for(let x=0;x<=cw;x+=22)ctx.lineTo(x,ch*.68+Math.sin(x*.03)*8);ctx.lineTo(cw,ch);ctx.lineTo(0,ch);ctx.fill();[[28,.62,16,26],[48,.58,20,32],[74,.64,14,22],[98,.60,18,28]].forEach(([x,fy,w,h])=>{const y=ch*fy;ctx.fillStyle='#2a241c';ctx.fillRect(x,y,w,h);ctx.fillStyle='#4a3a24';ctx.beginPath();ctx.moveTo(x-2,y);ctx.lineTo(x+w/2,y-h*.38);ctx.lineTo(x+w+2,y);ctx.fill();ctx.fillStyle='#c9a44c';ctx.fillRect(x+w*.35,y+h*.45,3,3)});ctx.fillStyle='#3a3428';ctx.fillRect(0,ch*.86,cw,ch);ctx.fillStyle='#2a261c';ctx.fillRect(0,ch*.86,cw,7);for(let x=18;x<cw;x+=46){ctx.fillStyle='#323028';ctx.fillRect(x,ch*.78,16,ch*.08)}ctx.fillStyle='#222';ctx.fillRect(16,14,128,8);ctx.fillStyle=hp>40?'#4a7a4a':'#9b2c2c';ctx.fillRect(16,14,128*(Math.max(0,hp)/100),8)}
function wyvern(s){ctx.fillStyle='#5a241c';ctx.beginPath();ctx.ellipse(0,4,s*.85,s*.28,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-s*.2,0);ctx.quadraticCurveTo(-s*.05,-s*1.15,s*.7,-s*.15);ctx.quadraticCurveTo(s*.1,-s*.1,-s*.2,0);ctx.fill();ctx.beginPath();ctx.moveTo(-s*.15,6);ctx.quadraticCurveTo(s*.1,s*1.05,s*.65,s*.2);ctx.fill();ctx.fillStyle='#3a1612';ctx.beginPath();ctx.moveTo(s*.55,-s*.08);ctx.lineTo(s*1.2,-s*.22);ctx.lineTo(s*1.15,s*.08);ctx.closePath();ctx.fill();ctx.fillStyle='#2a100c';ctx.beginPath();ctx.moveTo(s*1.12,-s*.18);ctx.lineTo(s*1.32,-s*.28);ctx.lineTo(s*1.18,-s*.06);ctx.fill();ctx.fillStyle='#e8dcc4';ctx.beginPath();ctx.arc(s*.92,-s*.14,s*.07,0,7);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(s*.95,-s*.14,s*.03,0,7);ctx.fill()}
function iron(s){ctx.fillStyle='#3d3a32';ctx.beginPath();ctx.ellipse(0,s*.12,s*.85,s*.42,0,0,7);ctx.fill();ctx.fillStyle='#5a5348';ctx.fillRect(-s*.5,-s*.05,s*.35,s*.28);ctx.fillRect(-s*.1,-s*.08,s*.4,s*.3);ctx.fillStyle='#2a281e';ctx.beginPath();ctx.ellipse(s*.7,-s*.05,s*.38,s*.3,0,0,7);ctx.fill();ctx.strokeStyle='#c9b48a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s*.85,-s*.18);ctx.lineTo(s*1.25,-s*.42);ctx.moveTo(s*.88,s*.08);ctx.lineTo(s*1.22,s*.22);ctx.stroke();ctx.fillStyle='#c9a44c';ctx.fillRect(s*.55,-s*.02,s*.22,s*.1)}
function drake(s){ctx.fillStyle='#4a5a28';ctx.beginPath();ctx.ellipse(-s*.1,s*.08,s*.8,s*.28,-.2,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-s*.3,-s*.05);ctx.quadraticCurveTo(s*.05,-s*.7,s*.55,-s*.05);ctx.fill();ctx.fillStyle='#2e3a18';ctx.beginPath();ctx.ellipse(s*.7,-s*.02,s*.32,s*.22,0,0,7);ctx.fill();ctx.fillStyle='#c33';ctx.beginPath();ctx.arc(s*.82,-s*.08,s*.05,0,7);ctx.fill()}
function stag(s){ctx.fillStyle='#4a3828';ctx.beginPath();ctx.ellipse(-s*.05,s*.14,s*.75,s*.32,0,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(s*.55,-s*.08,s*.28,s*.3,0,0,7);ctx.fill();ctx.strokeStyle='#2a2014';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s*.5,-s*.32);ctx.lineTo(s*.28,-s*1.05);ctx.lineTo(s*.12,-s*.7);ctx.moveTo(s*.58,-s*.32);ctx.lineTo(s*.82,-s*1.08);ctx.lineTo(s*1.0,-s*.68);ctx.stroke();ctx.fillStyle='#1a1010';ctx.beginPath();ctx.arc(s*.68,-s*.12,s*.05,0,7);ctx.fill()}
function wraith(s){ctx.fillStyle='#2a3a4a';ctx.beginPath();ctx.moveTo(0,-s*.9);ctx.quadraticCurveTo(s*.7,0,0,s*.95);ctx.quadraticCurveTo(-s*.7,0,0,-s*.9);ctx.fill();const g=ctx.createRadialGradient(0,-s*.1,2,0,-s*.1,s*.45);g.addColorStop(0,'#d8f0ff');g.addColorStop(1,'rgba(40,70,90,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,-s*.1,s*.4,0,7);ctx.fill()}
function hydra(s){ctx.strokeStyle='#245830';ctx.lineWidth=s*.22;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-s,s*.25);ctx.bezierCurveTo(-s*.4,-s*.55,s*.15,s*.55,s*.55,0);ctx.stroke();ctx.beginPath();ctx.moveTo(-s*.6,s*.3);ctx.bezierCurveTo(-s*.1,-s*.9,s*.4,s*.2,s*.7,-s*.25);ctx.stroke();ctx.fillStyle='#1c4024';ctx.beginPath();ctx.ellipse(s*.75,-s*.22,s*.28,s*.18,-.2,0,7);ctx.fill();ctx.fillStyle='#c33';ctx.beginPath();ctx.moveTo(s*.95,-s*.3);ctx.lineTo(s*1.18,-s*.22);ctx.lineTo(s*.95,-s*.14);ctx.fill()}
function roc(s){ctx.fillStyle='#6a5340';ctx.beginPath();ctx.ellipse(0,s*.06,s*.7,s*.32,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-s*.35,-s*.05);ctx.lineTo(-s*.15,-s*1.15);ctx.lineTo(s*.75,-s*.1);ctx.closePath();ctx.fill();ctx.fillStyle='#4a382c';ctx.beginPath();ctx.ellipse(s*.55,-s*.02,s*.32,s*.22,0,0,7);ctx.fill();ctx.fillStyle='#c9a44c';ctx.beginPath();ctx.moveTo(s*.75,-s*.04);ctx.lineTo(s*1.18,0);ctx.lineTo(s*.75,s*.08);ctx.fill()}
const DRAW={wyvern,iron,drake,stag,wraith,hydra,roc};
function beast(b){const s=26+b.z*70;ctx.save();ctx.translate(b.x,b.y);ctx.globalAlpha=b.flash>0?.65:Math.min(1,.5+b.z*.5);(DRAW[b.draw]||wyvern)(s);ctx.globalAlpha=1;ctx.fillStyle='#222';ctx.fillRect(-s*.65,-s*1.22,s*1.3,5);ctx.fillStyle='#b33';ctx.fillRect(-s*.65,-s*1.22,s*1.3*Math.max(0,b.hp/b.max),5);if(b.rev){ctx.strokeStyle='#d4b45a';ctx.strokeRect(-s*.28,-s*.22,s*.55,s*.42);ctx.fillStyle='#d4b45a';ctx.font='12px Georgia';ctx.fillText(AMMO.find(a=>a.id===b.weak).n,-s*.55,-s*1.36)}ctx.restore()}
function warden(cw,ch){const p=pull;ctx.save();ctx.translate(kick?(Math.random()-.5)*kick:0,0);ctx.fillStyle='#2a2218';ctx.beginPath();ctx.moveTo(cw*.16,ch);ctx.quadraticCurveTo(cw*.32,ch*.72,cw*.48,ch*.78);ctx.lineTo(cw*.54,ch);ctx.fill();ctx.fillStyle='#3a2e22';ctx.beginPath();ctx.moveTo(cw*.84,ch);ctx.quadraticCurveTo(cw*.70,ch*.74,cw*.56,ch*.80);ctx.lineTo(cw*.64,ch);ctx.fill();ctx.strokeStyle='#c4a07a';ctx.lineWidth=15;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(cw*.28,ch*.98);ctx.quadraticCurveTo(cw*.26,ch*.78,cw*.42-p*8,ch*.61);ctx.stroke();ctx.fillStyle='#c4a07a';ctx.beginPath();ctx.ellipse(cw*.43-p*8,ch*.59,12,9,0,0,7);ctx.fill();ctx.strokeStyle='#6a4a28';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(cw*.40,ch*.40);ctx.quadraticCurveTo(cw*.53,ch*.57,cw*.41,ch*.78);ctx.stroke();ctx.strokeStyle='#d8c8a8';ctx.lineWidth=1.6;ctx.beginPath();ctx.moveTo(cw*.40,ch*.40);ctx.lineTo(cw*.35-p*32,ch*.59);ctx.lineTo(cw*.41,ch*.78);ctx.stroke();ctx.strokeStyle='#b8906c';ctx.lineWidth=14;ctx.beginPath();ctx.moveTo(cw*.74,ch);ctx.quadraticCurveTo(cw*.68,ch*.80,cw*.35-p*30,ch*.59);ctx.stroke();ctx.fillStyle='#b8906c';ctx.beginPath();ctx.ellipse(cw*.35-p*30,ch*.59,11,8,0,0,7);ctx.fill();ctx.fillStyle='#5a4030';ctx.fillRect(cw*.32-p*30,ch*.55,17,10);ctx.restore();ctx.strokeStyle='rgba(212,180,90,.9)';ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(aim.x,aim.y,11,0,7);ctx.stroke();ctx.beginPath();ctx.moveTo(aim.x-18,aim.y);ctx.lineTo(aim.x-6,aim.y);ctx.moveTo(aim.x+6,aim.y);ctx.lineTo(aim.x+18,aim.y);ctx.moveTo(aim.x,aim.y-18);ctx.lineTo(aim.x,aim.y-6);ctx.moveTo(aim.x,aim.y+6);ctx.lineTo(aim.x,aim.y+18);ctx.stroke()}
function loop(now){const dt=Math.min(.033,(now-(loop.t||now))/1000);loop.t=now;t+=dt;const cw=canvas.clientWidth,ch=canvas.clientHeight;ctx.setTransform(dpr,0,0,dpr,0,0);sky(cw,ch);pull=Math.max(0,pull-dt*3);kick=Math.max(0,kick-dt*18);cool=Math.max(0,cool-dt);if(state==='play'){if(studying){const n=nearAt(aim.x,aim.y);observe=Math.min(1,observe+dt*(n?1.15:.12));if(n&&observe>=1){n.rev=1;say(n.name+': '+n.tell);observe=0;studying=0}}else observe=Math.max(0,observe-dt*.5);beasts.forEach(b=>{if(!b.ok)return;b.ph+=dt*b.sp;b.z=Math.min(1.12,b.z+dt*.06*b.sp);b.x+=Math.sin(b.ph*1.2)*14*dt;b.y+=Math.cos(b.ph*.7)*7*dt;b.x=Math.max(cw*.3,Math.min(cw*.92,b.x));b.y=Math.max(ch*.2,Math.min(ch*.6,b.y));b.flash=Math.max(0,b.flash-dt);if(b.z>.96)b.atk+=dt;if(b.atk>1.65){b.atk=0;hp=Math.max(0,hp-b.dmg);kick=12;burst(cw*.5,ch*.55,'#9b2c2c',14);say(b.name+' hits the wall. \u2212'+b.dmg);hud();if(hp<=0)lose()}});beasts.filter(b=>b.ok).sort((a,c)=>a.z-c.z).forEach(beast);arrows.forEach(a=>{a.t+=dt/.18;const x=a.x+(a.tx-a.x)*Math.min(1,a.t),y=a.y+(a.ty-a.y)*Math.min(1,a.t);ctx.strokeStyle=AMMO.find(z=>z.id===a.ammo).c;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-12,y-5);ctx.lineTo(x+9,y+3);ctx.stroke();if(a.t>=1&&!a.hit){a.hit=1;const n=nearAt(a.tx,a.ty);if(n)strike(n,a.ammo);else say('The shaft hits stone.')}});arrows=arrows.filter(a=>a.t<1.2);bits.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});bits=bits.filter(p=>p.life>0);bits.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.s,p.s);ctx.globalAlpha=1});if(studying||observe>0){ctx.strokeStyle='rgba(212,180,90,'+(.35+observe*.65)+')';ctx.beginPath();ctx.arc(aim.x,aim.y,24+observe*14,-1.57,-1.57+6.28*observe);ctx.stroke()}if(!busy&&beasts.length&&beasts.every(b=>!b.ok)){busy=1;if(wave>=con.w)win();else spawn()}}warden(cw,ch);requestAnimationFrame(loop)}
function aimFrom(e){const r=canvas.getBoundingClientRect();const s=e.touches?e.touches[0]:e;aim.x=s.clientX-r.left;aim.y=s.clientY-r.top}
canvas.addEventListener('mousemove',aimFrom);
canvas.addEventListener('mousedown',e=>{if(e.button===0)shoot();if(e.button===2)studying=1});
canvas.addEventListener('mouseup',e=>{if(e.button===2)studying=0});
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('touchstart',e=>{e.preventDefault();aimFrom(e);if(e.touches.length>1)studying=1;else shoot()},{passive:false});
canvas.addEventListener('touchmove',e=>{e.preventDefault();aimFrom(e)},{passive:false});
canvas.addEventListener('touchend',()=>studying=0);
addEventListener('keydown',e=>{if(e.key==='Shift')studying=1;const a=AMMO.find(x=>x.k===e.key);if(a){ammo=a.id;ammoUI()}});
addEventListener('keyup',e=>{if(e.key==='Shift')studying=0});
size();ammoUI();hud();menu();requestAnimationFrame(loop);
